/**
 * Creating a sidebar enables you to:  - Create an ordered group of docs
 * - Render a sidebar from the docs folder structure
 * - Create a sidebar from a custom category
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
